//! Adversarial corpus regression guard.
//!
//! Cases are generated by `tools/adversarial/generate_adversarial.py`; the
//! attack analysis lives in `tools/adversarial/ATTACKS.md`. The strings below
//! are pasted verbatim from that generator (deterministic output, bitwidth 64).
//!
//! Two invariants are enforced:
//!
//!  * SOUNDNESS (hard): the pipeline must never present a `Simplified` result
//!    that is not equivalent to its input. A false accept fails the suite. This
//!    is the load-bearing guard — it must hold for every input, forever.
//!  * COMPLETENESS (informational): we report which known-hard inputs the
//!    engine collapses vs. misses. Misses are documented limitations and do not
//!    fail CI, but the printed report makes regressions/improvements visible
//!    (run with `-- --nocapture`).
//!
//! `spot_check_is_fooled_by_precomputed_seed_trap` is a *characterization*
//! test: it proves the bounded, deterministically-seeded full-width check can
//! be evaded. When the verifier is hardened (seed salt, 3-var probes, more
//! samples, or a mandatory solver/Lean gate), that test will start failing —
//! that is the signal to update it, not a regression.

use cobra_core::evaluator::Evaluator;
use cobra_core::expr::Expr;
use cobra_core::expr_rewrite::build_var_support;
use cobra_core::expr_utils::remap_var_indices;
use cobra_core::simplify_outcome::{Options, SimplifyOutcomeKind};
use cobra_core::spot_check::{eval_expr, full_width_check_eval, DEFAULT_NUM_SAMPLES};
use cobra_parser::parse_to_ast;
use cobra_passes::simplify_expr;

const BITWIDTH: u32 = 64;

/// A completeness case: an obfuscated input known to equal `target`.
struct Case {
    name: &'static str,
    /// Obfuscated input fed to the engine.
    input: &'static str,
    /// A known-equivalent simpler form the engine *ought* to reach.
    target: &'static str,
}

/// Generated by `generate_adversarial.py --family all --nvars 6` /
/// `--nvars <n>` per family. Each `input` is self-checked equivalent to
/// `target` by the generator before emission.
const COMPLETENESS: &[Case] = &[
    Case {
        name: "A1 wide-bitwise-atom (>5-var AND forces opaque atom)",
        input: "(v0 & v1 & v2 & v3 & v4 & v5) + (v0 | v1 | v2 | v3 | v4 | v5) - (v0 & v1 & v2 & v3 & v4 & v5)",
        target: "v0 | v1 | v2 | v3 | v4 | v5",
    },
    Case {
        name: "A2 variable-wall (12-var linear identity)",
        input: "(v0 ^ 0) + (v1 ^ 0) + (v2 ^ 0) + (v3 ^ 0) + (v4 ^ 0) + (v5 ^ 0) + (v6 ^ 0) + (v7 ^ 0) + (v8 ^ 0) + (v9 ^ 0) + (v10 ^ 0) + (v11 ^ 0) + 123 - 123",
        target: "v0 + v1 + v2 + v3 + v4 + v5 + v6 + v7 + v8 + v9 + v10 + v11",
    },
    Case {
        name: "A3 high-degree-poly (degree-12 carrier)",
        input: "a ** 12 - a ** 12 + a + b",
        target: "a + b",
    },
    Case {
        name: "A5 unknown-shape (bitwise-over-arith, no mul)",
        input: "-(a + (b & (c + d))) - 1",
        target: "~(a + (b & (c + d)))",
    },
    Case {
        name: "A6 non-polynomial-shift (a == (a>>1)*2 + (a&1))",
        input: "(a >> 1) * 2 + (a & 1)",
        target: "a",
    },
    // Genuine, non-cancelling MBA identities (no trivially-vanishing carrier).
    // These require the real signature/decomposition machinery, so they are
    // the cases most likely to surface a missed simplification.
    Case {
        name: "B-xor2 ((a|b)-(a&b) == a^b)",
        input: "(a | b) - (a & b)",
        target: "a ^ b",
    },
    Case {
        name: "B-xor3 (arithmetic popcount form == a^b^c)",
        input: "a + b + c - 2*((a&b)+(a&c)+(b&c)) + 4*(a&b&c)",
        target: "a ^ b ^ c",
    },
    // xor-mask-wall: a ^ (a & M) == a & ~M. This used to be the headline
    // missed-simplification family: solved only while the bitwise atom's
    // support stayed <=4 variables, and missed at >=5 (input echoed back, or
    // blown up). Now fixed by two complementary changes:
    //   1. the certified `XorAndEqAndNot64` rewrite (`x ^ (x & y) -> x & ~y`),
    //      applied at seed time and during late candidate normalization;
    //   2. an anti-bloat gate in the main loop that drops bit-partition
    //      reconstructions which explode past ~4x the input size, so the
    //      cheaper rewrite wins instead of the sum-of-products canonicalisation.
    // The 7- and 8-variable cases below are where upstream CoBRA (C++) still
    // emits the bloated sum-of-products; our engine now returns `a & ~M`.
    // These cases are regression guards: a regression reappears as a miss in
    // the report below.
    Case {
        name: "C-xormask-3 (a^(a&(b|c)) == a&~(b|c))",
        input: "a ^ (a & (b | c))",
        target: "a & ~(b | c)",
    },
    Case {
        name: "C-xormask-5 (a^(a&(b|c|d|e)) == a&~(b|c|d|e))",
        input: "a ^ (a & (b | c | d | e))",
        target: "a & ~(b | c | d | e)",
    },
    Case {
        name: "C-xormask-6 (a^(a&(b|c|d|e|f)) == a&~(b|c|d|e|f))",
        input: "a ^ (a & (b | c | d | e | f))",
        target: "a & ~(b | c | d | e | f)",
    },
    Case {
        name: "C-xormask-7 (beats C++: a^(a&(b..g)) == a&~(b..g))",
        input: "a ^ (a & (b | c | d | e | f | g))",
        target: "a & ~(b | c | d | e | f | g)",
    },
    Case {
        name: "C-xormask-8 (beats C++: a^(a&(b..h)) == a&~(b..h))",
        input: "a ^ (a & (b | c | d | e | f | g | h))",
        target: "a & ~(b | c | d | e | f | g | h)",
    },
    // A7 budget-exhaustion is included with a shorter nest so the test stays
    // fast; the engine must still never emit a wrong simplification.
    Case {
        name: "A7 budget-exhaustion (depth-24 *1 nest)",
        input: "((((((((((((((((((((((((a) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)) * (b - b + 1)",
        target: "a",
    },
];

// ---------------------------------------------------------------------------
// Independent equivalence oracle (does not reuse the engine's spot-check).
// ---------------------------------------------------------------------------

fn splitmix(state: &mut u64) -> u64 {
    *state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut z = *state;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// Probe points: edge values applied to all vars, single-var edge values, and
/// many fully-random points with independent per-variable values (the probe
/// pattern the engine's own checker is weakest at).
fn probe_points(num_vars: usize) -> Vec<Vec<u64>> {
    let edges: [u64; 9] = [0, 1, u64::MAX, u64::MAX - 1, 2, 3, 5, 7, 1u64 << 63];
    let mut pts = Vec::new();
    for &e in &edges {
        pts.push(vec![e; num_vars]);
    }
    for v in 0..num_vars {
        for &e in &edges {
            let mut p = vec![0u64; num_vars];
            p[v] = e;
            pts.push(p);
        }
    }
    let mut state = 0x5151_A5A5_C0B7_A001u64;
    for _ in 0..512 {
        pts.push((0..num_vars).map(|_| splitmix(&mut state)).collect());
    }
    pts
}

/// Returns `Some(point)` if `a` and `b` disagree at some probe point, else
/// `None`. `a` and `b` must share the same variable space/arity.
fn first_disagreement(a: &Expr, b: &Expr, num_vars: usize) -> Option<Vec<u64>> {
    for pt in probe_points(num_vars) {
        if eval_expr(a, &pt, BITWIDTH) != eval_expr(b, &pt, BITWIDTH) {
            return Some(pt);
        }
    }
    None
}

/// Tree size used as a complexity proxy: an "equivalent but not smaller"
/// output means the engine failed to reduce, i.e. a missed simplification.
fn node_count(expr: &Expr) -> usize {
    1 + expr.children.iter().map(|c| node_count(c)).sum::<usize>()
}

/// Remap a simplified expression that lives in a reduced `real_vars` space back
/// into the full `all_vars` space, mirroring the CLI's presentation path.
fn lift_to_full_space(expr: &Expr, all_vars: &[String], real_vars: &[String]) -> Expr {
    if real_vars.is_empty() || real_vars.len() >= all_vars.len() {
        return expr.clone();
    }
    let idx_map = build_var_support(all_vars, real_vars);
    let mut owned = expr.clone();
    remap_var_indices(&mut owned, &idx_map);
    owned
}

// ---------------------------------------------------------------------------
// SOUNDNESS GUARD + COMPLETENESS REPORT
// ---------------------------------------------------------------------------

#[test]
fn corpus_never_emits_a_nonequivalent_simplification() {
    let mut solved = 0usize;
    let mut missed: Vec<String> = Vec::new();

    for case in COMPLETENESS {
        let parsed = parse_to_ast(case.input, BITWIDTH)
            .unwrap_or_else(|e| panic!("[{}] parse: {}", case.name, e.message));
        let original = parsed.expr.clone_tree();
        let num_vars = parsed.vars.len();
        let input_size = node_count(&original);

        let opts = Options {
            bitwidth: BITWIDTH,
            max_vars: 16,
            ..Options::default()
        };

        // The pipeline can legitimately reject some inputs (e.g. >max_vars);
        // treat an Err as a documented miss rather than a test failure.
        let outcome = match simplify_expr(&original, &parsed.vars, opts) {
            Ok(o) => o,
            Err(e) => {
                missed.push(format!("{} [pipeline rejected: {e:?}]", case.name));
                continue;
            }
        };

        match outcome.kind {
            SimplifyOutcomeKind::Simplified => {
                let raw = outcome
                    .expr
                    .as_ref()
                    .unwrap_or_else(|| panic!("[{}] Simplified without expr", case.name));
                let lifted = lift_to_full_space(raw, &parsed.vars, &outcome.real_vars);

                // HARD INVARIANT: a presented simplification must be equivalent
                // to its input. This is the false-accept guard.
                if let Some(pt) = first_disagreement(&original, &lifted, num_vars) {
                    panic!(
                        "[{}] SOUNDNESS VIOLATION: engine emitted a non-equivalent \
                         simplification.\n  input : {}\n  output: {}\n  differ at: {:?}",
                        case.name,
                        case.input,
                        cobra_core::expr::render(&lifted, &parsed.vars, BITWIDTH),
                        pt,
                    );
                }

                // A genuine simplification must reduce complexity. An
                // equivalent-but-not-smaller (or larger) result is a miss: the
                // engine returned the input or blew it up.
                let out_size = node_count(&lifted);
                if out_size < input_size {
                    solved += 1;
                } else {
                    missed.push(format!(
                        "{} [no reduction: {input_size} -> {out_size} nodes]",
                        case.name
                    ));
                }
            }
            SimplifyOutcomeKind::UnchangedUnsupported | SimplifyOutcomeKind::Error => {
                missed.push(format!("{} [unsupported]", case.name));
            }
        }
    }

    eprintln!(
        "\n=== adversarial completeness report ===\n\
         solved (reduced): {}/{}   missed: {}",
        solved,
        COMPLETENESS.len(),
        missed.len(),
    );
    for m in &missed {
        eprintln!("  MISSED: {m}");
    }
    eprintln!("=======================================\n");

    // Only the soundness invariant fails the test. Misses are the documented
    // attack surface (ATTACKS.md) — recorded here so a regression that turns a
    // currently-solved case into a miss (or vice-versa) is visible in CI logs.
}

// ---------------------------------------------------------------------------
// VERIFIER-EVASION REGRESSION GUARD (B1)
// ---------------------------------------------------------------------------

/// A precomputed-seed trap that USED to fool `full_width_check_eval`: `g`
/// (original) and `f` (candidate) are inequivalent, but `g`'s extra term was
/// engineered to vanish on every adversarial/single-var probe and on the 8
/// random points drawn by the *old* `seed_for(num_vars=3, bitwidth=64,
/// num_samples=8)` schedule (which depended only on those three scalars).
///
/// The seed is now salted with a structural fingerprint of the original and
/// candidate (see `cobra-core::spot_check::seed_for` /
/// `Evaluator::structural_fingerprint`), so the trap's roots feed back into the
/// seed and the random probe points no longer coincide with them. The check
/// must now CATCH the trap (report `!passed`).
///
/// Trap generated by:
///   `generate_adversarial.py --family soundness_trap --nvars 3 --samples 8`
/// If this test starts failing (the check passes again), the seed-binding fix
/// has regressed — the verifier is once more evadable by a fixed-seed trap.
#[test]
fn precomputed_seed_trap_is_now_caught_by_salted_probe() {
    let g_src = "(v0 + v1 + v2) + (v0 * v1 * v2 * (v0 - v1) \
        * (v0 - 924774547064411935) * (v0 - 8915036522582361283) \
        * (v0 - 9484185179004083879) * (v0 - 9536981162489986658) \
        * (v0 - 11338581770329482960) * (v0 - 12632878057438767332) \
        * (v0 - 16312441918215010300) * (v0 - 18279994418780881162))";
    let f_src = "v0 + v1 + v2";

    let g = parse_to_ast(g_src, BITWIDTH).unwrap();
    let f = parse_to_ast(f_src, BITWIDTH).unwrap();
    assert_eq!(
        g.vars, f.vars,
        "trap and candidate must share variable space"
    );
    let num_vars = g.vars.len() as u32;

    // Ground truth: f and g are genuinely inequivalent (witness (3,6,9)).
    let witness = [3u64, 6, 9];
    assert_ne!(
        eval_expr(&g.expr, &witness, BITWIDTH),
        eval_expr(&f.expr, &witness, BITWIDTH),
        "precondition: trap must actually differ from candidate",
    );

    // The salted check is built from the ORIGINAL (g), exactly as the pipeline
    // does, and must now reject the inequivalent candidate.
    let eval_g = Evaluator::from_expr(&g.expr, BITWIDTH);
    let check = full_width_check_eval(&eval_g, num_vars, &f.expr, BITWIDTH, DEFAULT_NUM_SAMPLES);

    assert!(
        !check.passed,
        "REGRESSION: a fixed-seed trap slipped past the full-width check. The \
         probe seed must stay bound to the expression fingerprint (see \
         tools/adversarial/ATTACKS.md)."
    );
}
